[package]
name = "scanner_3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
glam = "0.25.0"
image = "0.24.8"
ndarray = "0.15.6"
rerun = "0.12.1"
