name: Raspberry Release

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  server:
    runs-on: self-hosted
    steps:
    - name: Build
      run: |
        docker run --rm ghcr.io/albertocenzato/scanner-3d-dev:1.3 sh -c \
           "git clone https://github.com/AlbertoCenzato/3d_scanner.git && \
            cd 3d_scanner && \
            cargo build --bin scanner_3d"
