name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  server:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Cache dependencies
      uses: actions/cache@v4.2.1
      with:
        path: |
          ~/.cargo
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build server
      run: cargo build --no-default-features --bin server

  rerun-support:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Cache dependencies
      uses: actions/cache@v4.2.1
      with:
        path: |
          ~/.cargo
          target
        key: ${{ runner.os }}-cargo-rerun-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build with Rerun support
      run: cargo build --no-default-features --features rerun --bin server

  ui:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Cache dependencies
      uses: actions/cache@v4.2.1
      with:
        path: |
          ~/.cargo
          target
        key: ${{ runner.os }}-cargo-ui-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build UI
      run: |
        cargo install --locked trunk
        cd scanner_ui
        trunk build

